### ISSUE TITLE
RndG question & proposal (probabilty)

### ISSUE THREAD

**Issue by firolightfog** [docb/dbRackModules#10]
According to the manual "the probabilities can be provided via the polyphonic prop input *(0-10V)*". Isn't it "*-5 to 5V*"?

<img width="547" alt="image" src="https://user-images.githubusercontent.com/34127628/149096217-12cada02-4a51-4fb4-9f27-52858e9aa4dc.png">

Would you please consider allowing an option in the *"context menu" to set the default probability*? Currently it's set ~~100%~~ 50% I believe but I usually use a separate fix voltage module to set it to 90% or so. What a waste of space and cables! :) 

Just a few common values like:
```
Default probability:
  * 100%
  * 95%
  * 85%
  * 70%
  * 50%
  * 30%
  * 15%
  * 5%
  * 0%
```

Best regards, Andras

**Comment by docb** [comment]
hi Andras, yes its wrong in the manual, -5V to 5V is correct. and the default is 0V = 50% (i have fixed it).
it can make sense to allow different default values if there is no cable connected.
however if there is only a mono volt input it should be used for all channels.
the idea was even if you want to provide different values for each channel a bogaudio polycon16 does not cost much space and cables compared to the count modula module.
![rgate](https://user-images.githubusercontent.com/1134412/149498075-36a709db-0bf7-462b-a03d-f39b2640fce6.png)
 
best regards,
Christian

**Comment by firolightfog** [comment]
Most probably I'll use the 'context menu' option (or a monoinput for *Prob*) for all channels anyway. 

Thanks for the clarification Christian!
