### ISSUE TITLE
RndC & RndH layout (minor issue)

### ISSUE THREAD

**Issue by firolightfog** [docb/dbRackModules#11]
It's a (very-)low-priority issue but anyway... 
- "Clk" is preferred instead of "CLK" for RndH.
- "Rst" is preferred instead of "RST" for RndH & RndC.
- Pushbutton of RndC is preferred location is lower.

<img width="108" alt="image" src="https://user-images.githubusercontent.com/34127628/149127427-ade9bf92-41bc-4b6b-8719-08bd825c3f76.png">

**Comment by docb** [comment]
ok thanks, makes sense to make it  consistent.
best regards,
christian

**Comment by docb** [comment]
Solved
