### ISSUE TITLE
RndG clock output PW proposal

### ISSUE THREAD

**Issue by firolightfog** [docb/dbRackModules#12]
The Clock output of RndG seems to be sending triggers. I don't think it's right. Would you please consider using the same pulse width (PW) as the original clock input? 

Just to show what I mean I set up this patch:

<img width="494" alt="image" src="https://user-images.githubusercontent.com/34127628/149548885-8ccd938c-716a-4f5d-a44a-dccf1c4f3188.png">

And I got this result:

<img width="403" alt="image" src="https://user-images.githubusercontent.com/34127628/149548923-3f06862e-da1d-4cf1-a17d-ecff421ff708.png">

The purple one is just a trigger2 output now. 

Cheers, A.

P.S.: The slew limiter ([Slade](https://library.vcvrack.com/squinkylabs-plug1/squinkylabs-slew4)) module was added just to make sure that all pulses are visible.

**Comment by docb** [comment]
Ah yes, thanks, of course it should reflect the clock, comes in next version,
best christian

**Comment by docb** [comment]
Solved
