### ISSUE TITLE
RndG Prob input issue

### ISSUE THREAD

**Issue by firolightfog** [docb/dbRackModules#14]
I believe that the Prob input of RndG is messed up some very strange way. Or I am. 

Feeding 5V to Prob I'd expect to see 100% of the pulses. (See purple signal.)

<img width="471" alt="image" src="https://user-images.githubusercontent.com/34127628/149612636-d8b57cf9-5a37-47d9-8525-a5d1664b1e8a.png">

**Comment by docb** [comment]
hi Andras,
i think this behaves correct:

the trig output only fires if the gate goes from 0 to 10.
if you set prop to 100% the gate stays at 10V and no trig will come.

![rgate2](https://user-images.githubusercontent.com/1134412/149628029-d481b0b5-ff44-4653-a12a-99b1bce194b0.png)

the clock output will fire as long the gate is 10V.
best regards,
Christian

**Comment by firolightfog** [comment]
I'm closing the case. I can't recreate my original error. I don't know how I did it.

Checked again and everything works as it should.

<img width="609" alt="image" src="https://user-images.githubusercontent.com/34127628/149637191-8676b04f-3d88-4604-9154-842800d507ee.png">

**Comment by firolightfog** [comment]
I'm reopening the ticket. Something is not right with this module.

In my previous test I sent the same signal to all channels and I saw some variation in the Clk output. (In my original bug report I checked the Trig output.)

But if I send various rhythms on the poly channels and a Prob input is provided (e.g. 5V for 100%) then
- Trig output is empty
- Clk output repeats the first channel

<img width="287" alt="image" src="https://user-images.githubusercontent.com/34127628/149680050-16ce1ff8-5738-49b0-a900-87a74b5f7fee.png">

Regards, Andras

**Comment by docb** [comment]
hi Andras, the clock input is definitely  monophonic currently. sorry, i didn't have had a usecase for a polyphonic clock input so I didn't implement it yet. But i think it is doable for the next version.
best regards,
Christian

**Comment by docb** [comment]
hi Andras, here is a dev version which fixes #11 #12 #14

https://github.com/docb/dbRackModules/releases/tag/2.0.5-dev-1

best regards, Christian

**Comment by firolightfog** [comment]
Some truly wonderful and important improvements! Seeing the quick tests below I'd encourage you to promote this version to the Library. However I'm still confused what to expect from the Trg output of RndG. 

#11 RndC, RndH, RndG panel improvements look great
#12 RndG Clk output PW is fixed for common clock inputs and works great

![image](https://user-images.githubusercontent.com/34127628/149947479-675e08b4-f06e-479e-965e-1bb21530f280.png)

#14 RndG Prob input works nicely with poly input signal

![image](https://user-images.githubusercontent.com/34127628/149949488-c5802e99-0066-4a56-ade9-8e9be68f6efd.png)

#14 RndG Prob handles easily if the number of channels in poly input is different from the RndG Chn settings 

![image](https://user-images.githubusercontent.com/34127628/149949792-792c2970-ff5d-4d64-9215-4184d66f6402.png)

#14 RndG Clk doesn't repeat the first channel for polyphonic output but handles the poly input of Clk nicely

![image](https://user-images.githubusercontent.com/34127628/149951349-39d2b413-84c6-43d4-94c0-1b7c9e5a79c0.png)

This is great! Thank you Christian!

Cheers, A.

**Comment by docb** [comment]
hi Andras, thanks for verifying. 
to verify the correctness of the trig output you always have to compare the trig output with the gate output. the trig output fires if the gate goes from 0 to 10. the clock outputs the clock input iff the gate is 10V.
note that LA-108 and LA-216 do not show triggers correctly - there are always missing triggers - the gate must be made longer for correct results. look at this: the top line direct and the bottom line with lengthen gates:

![la-216](https://user-images.githubusercontent.com/1134412/149971855-16b37873-56aa-4d27-be13-13f83db74d28.png)

however still here is a trigger missing. but i don't trust the LA-216 ...
best regards,
Christian

**Comment by firolightfog** [comment]
I got it now. You are right with the trigger and the analyzer... RndG seems to be working perfectly. :)

<img width="540" alt="image" src="https://user-images.githubusercontent.com/34127628/150006379-c6f0f668-8f85-45e8-832c-8b50515bb36e.png">

I think all #11, #12, #14 can be closed with the docB v2.0.5 release.

Best regards, Andras

**Comment by docb** [comment]
Solved
