### ISSUE TITLE
module request: Poisson trigger

### ISSUE THREAD

**Issue by glocke01** [docb/dbRackModules#15]
If you could make a module that sent out triggers separated by an exponentially distributed random time (i.e. a Poisson process), that'd be wonderful. HetrickCV Dust does this (with triggers of 1 sample duration), but it's optimized for audible noise so that it's very hard to select an average less than 10 Hz.

**Comment by docb** [comment]
hi thanks for your request,
i have to look a bit deeper, 
but isn't the module Rtrig with deviation = 1 doing this already or at least sufficiently similar?

**Comment by docb** [comment]
Closed due to inactivity
