### ISSUE TITLE
HexSeqP pattern jump CV (bug)

### ISSUE THREAD

**Issue by firolightfog** [docb/dbRackModules#17]
Dear Christian,

The built-in knob works fine for changing patterns but the CV behaves strangely. It should jump by 10V/16 steps, right? 

<img width="170" alt="image" src="https://user-images.githubusercontent.com/34127628/151415159-44470d20-55a2-4e13-b7d3-a315f06a47b0.png">

**Comment by firolightfog** [comment]
Oh,it's all good. I forgot the Poly Mode settings.

I'm closing the ticket.

**Comment by docb** [comment]
OK, here i wondered if it would be better that the CV mode ("non poly mode") should be the default?

**Comment by firolightfog** [comment]
I'd support changing the default to "non poly mode" (aka "CV controlled jump") cause some of the old, popular & well-known modules use this method by default. (Please see: Bogaudio ADDR-SEQ, 8:1, 1:8, as well as Hetrick Rotator.) So it seems to be more common.

After checking/unchecking it multiple times I also decided to set it accordingly in my module template preset. 

Best regards, Andras

**Comment by docb** [comment]
I will let as is for compatibility.
