### ISSUE TITLE
Knob behaviour

### ISSUE THREAD

**Issue by paulpiko** [docb/dbRackModules#19]
Rack 2.0.6, Windows

Using Pad. When using knobs, such as BW, Scl, the value of the knob doesn't seem to take effect until the mouse button is released. This is different to most knobs in rack and makes it harder to try different values. It also means the knobs don't work with Stoermelder uMap; the knobs can be turned using uMap but the new value is not applied

**Comment by docb** [comment]
hi, this is a technical restriction of the underlying algorithm and was made by intent. On a value change of any of the parameters some heavy calculations have do be done which would lead to audio clicks if handled in the normal way. However,  there may be some more sophisticated solutions for this problem. Thanks for indicating i planned to investigate anyway.

**Comment by docb** [comment]
@paulpiko, i have pushed a version into the development branch which contains the pad2 module.
if you are able to build then you could test it, or i can also make a dev preview release.
the solution is now an interesting experiment which works ok on linux so far:
the heavy processing is completely done in the background. 
the background processing it will not affect the CPU usage of the rack module at all, but the overall cpu usage of the computer will increase (so about 20% on one cpu). so you may notice that the fun of your computer may be noisier
if you make a lot of changes (also when connecting an lfo to the bw input). but if nothing is changed it will be quiet.

**Comment by paulpiko** [comment]
thanks, sounds interesting. can you make a Windows build?

**Comment by docb** [comment]
here it is:
[dbRackModules-2.1.0-win.zip](https://github.com/docb/dbRackModules/files/8789821/dbRackModules-2.1.0-win.zip)

**Comment by docb** [comment]
This issue is solved in 2.1.0
