### ISSUE TITLE
HexSeq and HexSeqP feature requests: Output Mode, and End Length Symbols

### ISSUE THREAD

**Issue by DaveBenham** [docb/dbRackModules#2]
Impressive and intriguing collection of modules!

I have two new feature suggestions for HexSeq and HexSeqP

1) Add an output mode switch with three states that controls the type of gate/trigger that is generated
 - Trigger (current behavior) = 1  generates 1 msec trigger at output
 - Gate = 1 replicates the incoming clock gate at the output
 - Latch mode = 1 sets output high until next 0.
                           0 sets output low until next 1.

If you wanted to go nuts the mode could be specified for each pattern. But I think a global mode would more than suffice.
HexSeq definitely has room for a global switch. Maybe you could squeeze in a switch into HexSeqP as well, but you can always add a context menu option.

2) Add new end length symbols that can be appended to the end of a sequence to specify how many bits are used from the last (previous) symbol. One possibility:
 - X = Only use first bit
 - Y = Use first two bits
 - Z = Use first three bits
 - No end length symbol = Use all four bits

Another possible set of symbols would be characters that pictorially represent the number of bits
- . (period) or - (dash) = 1 bit
- : (colon) or = (equal) = 2 bits
- % (percent) = 3 bits
-  If you wanted, you could use # for 4 bits, which would be the same as no end length symbol

Either way, this would allow all possible pattern lengths from 1-60, plus 64. Lengths of 61, 62, and 63 would still not be possible.

**Comment by docb** [comment]
Hi thanks for your interest and suggestions. 
1.) I think you mean in the case Gate = 1 that if the clock has say a 30 ms pulse it should be reflected i.e.set 30 ms high if the bit is set. I like the idea of the latch mode.
2.) Not sure about that yet -- have to think about. The feature is to have not the length restriction "times 4" and your suggestion would not require a new layout.
I will definitely have a look at it asap.

**Comment by DaveBenham** [comment]
Yes, my language was perhaps a bit obtuse for suggestion 1. Substitute the work "means" or "signifies" for the = sign, and the 1 represents a 1 (high) bit in the beat pattern. So yes, in Gate mode, for each clock tick that coincides with a 1 bit, the clock gate would be sent to the output. In your example, yes that would be a 30 ms pulse. The interesting thing is the clock gates need not have consistent lengths, and it will still work fine.

Instead of having an output mode, you could simply provide three simultaneous output ports, one for each of those modes. I think that would fit fine in HexSeq, but might be problematic for the existing HexSeqP layout.

The intention of my second request is to offer more flexibility in establishing polymeters that go in and out of phase.

I thought of a number of variations for both requests, but intentionally restricted the suggestions to what I thought would preserve your current design, yet would still be significant enhancements.

**Comment by docb** [comment]
![latchmode](https://user-images.githubusercontent.com/1134412/147989817-9fab5132-1c6c-4631-926c-18d08827e575.png)

i just played around a bit - this would be the latch mode made with other modules.

![gate](https://user-images.githubusercontent.com/1134412/147990872-6ff33300-1dba-4894-9b08-11753aa1f731.png)

and this the gate mode made with other modules.

**Comment by DaveBenham** [comment]
Yes, that looks good. Here is a single simpler patch that shows all 3 output modes. The Gate output is easily derived once you have the latch output. I've got all the signals timed so they arrive at the scope at the same time. I used the AND gate to introduce one extra sample delay without resorting to another SD module.

![HexSeq](https://user-images.githubusercontent.com/17756633/147995999-0b002582-d29a-494f-a2d9-31354a2703ab.PNG)

Red = Clock input
Yellow = Trigger output
Green = Latch output
Blue = Gate output

**Comment by docb** [comment]
hi Dave,
still in development/fixing but i have put a Release 2.0.4-dev for testing which covers the first request:
![hexseqnew](https://user-images.githubusercontent.com/1134412/148760777-b76e7c3c-ff99-4458-85be-3f5e8fe29c57.jpg)



as i have now fixed an issue to enable livecoding (which is an important feature) and added some random and shift operations, i think i would not do request 2 at this time as it adds complexity for the development and the user and somehow contradicts the aim of the module. still it is possible to clock times 2 or 4 to achieve more sequence lengths or by using the reset trigger. if i would dive in this i would rather make an expander with length adjustment knobs -3,-2,-1,0

Best regards,
Christian

**Comment by DaveBenham** [comment]
I like it!

**Comment by docb** [comment]
I will close this for now. Point one is done in 2.0.4 and there is a remainder ticket #16 for the second point.
