### ISSUE TITLE
Enhancement - PAD2/PAD Expander to sequence/load profiles

### ISSUE THREAD

**Issue by DaveBenham** [docb/dbRackModules#22]
PAD2 is great for discovering interesting sounds.

An expander could be used to store the current partial profile, as well as bandwidth, scale, etc. based on the press of a button (and maybe CV trigger input?)

The expander could have N slots, each with its own button for setting/recalling a given profile.

And there can be CV control to select any one of the slots on demand. And it can honor the slew that I suggested in another enhancement request. There can be a number of modes as to how the CV selects the each profile.

Basically I am talking about the functionality of Stoermelder's TRANSIT module, but dedicated to PAD and PAD2. TRANSIT has a large number of interesting selection modes.

The beauty of such an expander would be you could discover/dial in and store the sounds you want with PAD2, and then transfer the expander to PAD for a more compact combination that no longer needs the sound discovery UI of PAD2.

One thing I have not thought through is what the behavior of the PAD2 controls should be if they are modified after the expander specifies a given profile.

I see two different use cases for the expander
  - To create compact static "instruments" using customized PAD sounds. By static I mean that the partial profile and other parameters would likely not change once set up.
  - To sequence constantly evolving PAD sounds

One other idea is to have a mechanism to write out a given profile to an external file that can then be shared and loaded by others. There could be some interesting preset files distributed with the module(s)

**Comment by docb** [comment]
I haven't done anything yet with Stoermelder's TRANSIT (i will do, seems to a great one) but the first question arises: What would the expander actually do different or better than TRANSIT?

**Comment by docb** [comment]
Probably fixed by using the new Faders module. Pls open a new issue for things missing/
