### ISSUE TITLE
PLC unresponsive (Del, Ctrl-R)

### ISSUE THREAD

**Issue by firolightfog** [docb/dbRackModules#23]
PLC v2.1.0 doesn't seem to respond to common hotkeys like Ctrl-R (random) and Del/Backspace (delete module) in case of mouse-over. The same key combinations work fine if the module is previously marked (i.e. Shift-Click). 
Cheers, A.

**Comment by docb** [comment]
yes there is missing a line of code. fix comes in next version ....
but you can press 1,2 or 3 to fetch the values of a left placed Fader module.

**Comment by docb** [comment]
fixed in 2.1.4
