### ISSUE TITLE
HexSeq(P) - visual QoL suggestion (enhancement)

### ISSUE THREAD

**Issue by forever-withyou** [docb/dbRackModules#24]
I would like to propose making groups of 4 numbers more discernable, to make it easier to read - if you input long sequence (especially if its full of zeroes) it takes a bit of effort to edit correct number.

Here are my ideas as to how it could be done - maybe you, or someone else will happen to have some better idea... Personally I like the green highlight the most. I think somehow adding visual cue to numbers themself is better way, even grouping with different font color would be fine, just anything. Brighter lightbulb way is kinda flawed I think, because they tend to misalign with numbers on some zoom levels (on 100% is fine). 

![Photoshop_K0uLStgHMT](https://user-images.githubusercontent.com/28648242/181479249-53a7da2a-aebc-461d-a716-662d74b600cb.png)
![Photoshop_Ps2UZONKWh](https://user-images.githubusercontent.com/28648242/181479305-e8891a70-6de2-4315-90b3-a50ae939ead4.png)
![Photoshop_tlrc3cBXA3](https://user-images.githubusercontent.com/28648242/181479391-2d9b99d7-4b86-42a5-af63-f241ff0c569a.png)

**Comment by docb** [comment]
hi, i would go for the second suggestion and simply modify the background color.
