### ISSUE TITLE
Modules with "pattern manager" - QoL suggestion (enhancement)

### ISSUE THREAD

**Issue by forever-withyou** [docb/dbRackModules#25]
So this idea involves modules: Chords, AG, Faders, HexSeqP - so equally dbRackModules/dbRackSequencer - unless I missed something.

I think it would be very nice to have 2 new buttons for better and less annoying editing of (longer) pattern sequences:

1. delete pattern - deletes current pattern and moves all patterns after current pattern -1 position (so there is no gap after deletion)
2. new pattern - injects clean pattern on current position, moving all further patterns, including current one +1 position (creates gap on currently selected pattern number, moving all patterns as they are and preserving order, destroying only pattern 99)

**Comment by docb** [comment]
ok, makes sense. it would be first in the dbRackSequencer modules as this will updated next.

**Comment by docb** [comment]
Done:
dbRackModules 2.1.4: Faders
dbRackSequencer 2.1.0: Chords,JTChords,AG,P16A
Wont do for HexSeqP because of incompatibility - considering to make a HexSeqP2 module for this.
