### ISSUE TITLE
Can't use AUX as filename on Windows

### ISSUE THREAD

**Issue by SteveRussell33** [docb/dbRackModules#29]
You're going to have to rename the file as it's a reserved word and therefore the file won't compile on Windows.
https://duckduckgo.com/?t=ffab&q=Can%27t+use+AUX+as+filename+on+Windows&ia=web
This includes the name of the SVG file as well.

**Comment by docb** [comment]
woohoo ok, very thanks!
doesn't matter as AUX is a historical name i will think about another ../..
