### ISSUE TITLE
Interface Input bug - last seen voltage remains after cable removal

### ISSUE THREAD

**Issue by DaveBenham** [docb/dbRackModules#30]
I love the concept of the Interface module. But there is one significant bug with inputs - If you remove an input cable, the module continues to "see" the most recent input voltage. The only way to clear the persistent voltage is to patch in a cable that is carrying 0V.

**Comment by docb** [comment]
Thanks for your report, it is solved in
https://github.com/docb/dbRackModules/releases/tag/v2.2.2
