### ISSUE TITLE
AP Delay CV

### ISSUE THREAD

**Issue by DanGarman** [docb/dbRackModules#39]
I noticed that CV into the Delay input of AP didn't alter the delay that much, even with Delay input set to 100%, so I looked at the code and saw a factor of 0.001 which should probably be 0.01.

"    int del=params[DELAY_SAMP_PARAM].getValue()+
      clamp(inputs[DELAY_INPUT].getVoltage()*0.001f*params[DELAY_CV_PARAM].getValue()+params[DELAY_PARAM].getValue(),0.f,0.5f)*args.sampleRate;"

I enjoy your modules very much, btw

**Comment by docb** [comment]
Hi thanks for the report, indeed the factor should be much higher even 0.1. It will take some time to the next release maybe as workaround you may upscale before e.g. with Ofs.
