### ISSUE TITLE
HexSeq feature request (Ctrl-I & Ctrl-R)

### ISSUE THREAD

**Issue by firolightfog** [docb/dbRackModules#4]
What a charming module it is! :) Would you please consider enabling the options available in the context menu of VCV Rack?

I mean options like Ctrl-I to initialize the module ...

<img width="257" alt="image" src="https://user-images.githubusercontent.com/34127628/147972854-e86a82ea-8cfc-4f45-af25-bb37066a3115.png">

Or the handy Ctrl-R to add some short randomized strings ...

<img width="130" alt="image" src="https://user-images.githubusercontent.com/34127628/147973420-083e237e-9eba-462b-b3fd-e652eee4cf33.png">

Best regards, Andras

**Comment by docb** [comment]
Hi thanks for the hint, that this is missing!
I will plan it for the next release.

**Comment by firolightfog** [comment]
Proposals were reviewed and related changes implemented in v2.0.4
