### ISSUE TITLE
HexSeq bug report (template overwriting) 

### ISSUE THREAD

**Issue by firolightfog** [docb/dbRackModules#5]
The VCV Rack offers the opportunity to save a "default template" for every module. It's the same with HexSeq: I can and I did create a template for my startup. 

But HexSeq ignores any re-saving attempt. (I mean changing the template and trying to overwrite the old *..\Rack2\presets\dbRackModules\HexSeq\template.vcvm* .)  

Best regards

**Comment by docb** [comment]
This seems to be a VCVRack problem. I could exactly reproduce. But then i have done the following:
Clear template. And then Save Template again (this would be a workaround). 
And then surprisingly from now on the message 
"Overwrite template preset for docB HexSeq?" appears on the next try and the template is overwritten then.
 I don't know the reason may be i'll ask in the developer group.

**Comment by docb** [comment]
hi Andras, i cant reproduce this anymore, you?

**Comment by firolightfog** [comment]
Template saving behaves as expected. 
I can't reproduce the issue. Let's close it for now. 
¯\_(ö)_/¯

**Comment by docb** [comment]
ok, done.
