### ISSUE TITLE
HexSeq factory preset proposal

### ISSUE THREAD

**Issue by firolightfog** [docb/dbRackModules#8]
Dear Christian,

I collected a few drum patterns that I'd suggest to include with HexSeq as '[factory presets](https://vcvrack.com/manual/Presets)'. It'll make the learning curve steeper for new comers. The patterns are based on this collection: https://blog.landr.com/best-drum-patterns/

[Drum pattern presets.zip](https://github.com/docb/dbRackModules/files/7814229/Drum.pattern.presets.zip)

Regards, Andras

**Comment by docb** [comment]
Good idea, but i would like to add bpm information in the file path. is this info available for the intended bpm? otherwise i also can also guess the intended bpm.
thanks and best regards, christian

**Comment by firolightfog** [comment]
I'm not in favor of providing the intended BPM but originally the examples were like

```
120BPM Four on the floor
144BPM The trap beat
108BPM The Bo Diddley beat
165BPM The two beat
 90BPM Boom-bap
 94BPM Dembow
 96BPM Impeach the President
106BPM Iconic eighths
 65BPM 12/8 feel
122BPM Shuffle feel
```

Feel free to modify the filenames if you whish.

Best regards, Andras

**Comment by S0210** [comment]
I mean the BPMs above are correct but please remember that they're in 4/4. So clock multiplication is expected to receive the original tempo:

<img width="318" alt="image" src="https://user-images.githubusercontent.com/34127628/148233000-7fd2b6c7-1c31-469b-a5b1-ba6722b35d20.png">

**Comment by firolightfog** [comment]
I'm closing the case as v2.0.3 rolled out with basic pattern presets.
